/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import config.Koneksi;
import controller.*;
import model.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Date;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Alesha Naila
 */
public class DaftarPesanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DaftarPesanan.class.getName());
    private Pegawai current_pegawai;

    private java.util.List<Pelanggan> listPelanggan;
    private java.util.List<Pegawai> listPegawai;
//    private List<Pesanan> current_pesanan;
    /**
     * Creates new form DaftarPesanan
     */
    public DaftarPesanan() {
        initComponents();
    }

    public DaftarPesanan(Pegawai pegawai) {
        initComponents();
        this.current_pegawai = pegawai;
        loadPelanggan();
        loadPegawai();
        showTablePesanan(); 
        setInitButtons();
        
    }
    
    private void loadPelanggan() {
        PelangganController pc = new PelangganController();
        listPelanggan = pc.getAllPelanggan();
        
        pelanggan.removeAllItems();
        pelanggan.addItem("Pilih Pelanggan");
        for (Pelanggan p : listPelanggan) {
            pelanggan.addItem(p.getNama_pelanggan());
        }
    }
    
    private void loadPegawai() {
        PegawaiController pc = new PegawaiController();
        listPegawai = pc.getAllPegawai();
        
        pegawai.removeAllItems();
        pegawai.addItem("Pilih Pegawai");
        for (Pegawai p : listPegawai) {
            pegawai.addItem(p.getNama_pegawai());
        }
    }
    
    private void showTablePesanan() {
        DaftarPesananController controller = new DaftarPesananController();
        tablePesanan.setModel(controller.getDaftarPesananLengkap());
              
        hitungTotalPendapatan();
    }
    
    private void resetComponents() {
            id.setText(null);
            pelanggan.setSelectedIndex(0);
            pegawai.setSelectedIndex(0);
            
            Date terima = new Date();
            tglTerima.setDate(terima);
            Date selesai = new Date();
            tglSelesai.setDate(selesai);
            
            totalKg.setText(null);
            totalBiaya.setText(null);
            status.setSelectedIndex(0);
     }
    
    private void setInitButtons() {
        id.setEnabled(false);
        pelanggan.setEnabled(false);
        pegawai.setEnabled(false);
        tglTerima.setEnabled(false);
        tglSelesai.setEnabled(false);
        totalKg.setEnabled(false);
        totalBiaya.setEnabled(false);
        status.setEnabled(false);
        
        ubah.setEnabled(true);
        reset.setEnabled(false);
        simpan.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblDaftarPesanan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCariPesanan = new javax.swing.JTextField();
        filterStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesanan = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        pnlCopyright = new javax.swing.JPanel();
        copyright = new javax.swing.JLabel();
        lblIdItem = new javax.swing.JLabel();
        lblIdItem1 = new javax.swing.JLabel();
        lblIdItem2 = new javax.swing.JLabel();
        lblIdItem3 = new javax.swing.JLabel();
        lblIdItem4 = new javax.swing.JLabel();
        lblIdItem5 = new javax.swing.JLabel();
        lblIdItem6 = new javax.swing.JLabel();
        lblIdItem7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        tglTerima = new com.toedter.calendar.JDateChooser();
        tglSelesai = new com.toedter.calendar.JDateChooser();
        totalKg = new javax.swing.JTextField();
        totalBiaya = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        ubah = new javax.swing.JButton();
        pelanggan = new javax.swing.JComboBox<>();
        pegawai = new javax.swing.JComboBox<>();
        reset = new javax.swing.JButton();
        detail = new javax.swing.JButton();
        lblTotalPendapatan = new javax.swing.JLabel();
        cetakStruk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 244, 248));

        jPanel3.setBackground(new java.awt.Color(26, 75, 125));

        lblDaftarPesanan.setBackground(new java.awt.Color(26, 75, 125));
        lblDaftarPesanan.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblDaftarPesanan.setForeground(new java.awt.Color(240, 244, 248));
        lblDaftarPesanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDaftarPesanan.setText("Daftar Pesanan");
        lblDaftarPesanan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 244, 248), 2, true));

        jButton1.setBackground(new java.awt.Color(26, 75, 125));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 244, 248));
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDaftarPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblDaftarPesanan)
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCariPesanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCariPesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPesananKeyReleased(evt);
            }
        });

        filterStatus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        filterStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "IN PROGRESS", "SELESAI" }));
        filterStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterStatusItemStateChanged(evt);
            }
        });

        tablePesanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pesanan", "Pelanggan", "Pegawai", "Tgl. Diterima", "Tgl. Selesai", "Total Kg", "Total Biaya", "Status"
            }
        ));
        jScrollPane1.setViewportView(tablePesanan);

        simpan.setBackground(new java.awt.Color(76, 175, 80));
        simpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(240, 244, 248));
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        pnlCopyright.setBackground(new java.awt.Color(51, 51, 51));
        pnlCopyright.setForeground(new java.awt.Color(51, 51, 51));

        copyright.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        copyright.setForeground(new java.awt.Color(240, 244, 248));
        copyright.setText("140810240048 | 140810240066 |140810240080");

        javax.swing.GroupLayout pnlCopyrightLayout = new javax.swing.GroupLayout(pnlCopyright);
        pnlCopyright.setLayout(pnlCopyrightLayout);
        pnlCopyrightLayout.setHorizontalGroup(
            pnlCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCopyrightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyright)
                .addGap(302, 302, 302))
        );
        pnlCopyrightLayout.setVerticalGroup(
            pnlCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCopyrightLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(copyright))
        );

        lblIdItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdItem.setText("ID Pesanan :");

        lblIdItem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdItem1.setText("Pelanggan :");

        lblIdItem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdItem2.setText("Pegawai :");

        lblIdItem3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdItem3.setText("Tgl Diterima :");

        lblIdItem4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdItem4.setText("Tgl. Selesai :");

        lblIdItem5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdItem5.setText("Total Kg :");

        lblIdItem6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdItem6.setText("Total Biaya :");

        lblIdItem7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdItem7.setText("Status :");

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN PROGRESS", "SELESAI" }));

        ubah.setBackground(new java.awt.Color(0, 102, 255));
        ubah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ubah.setForeground(new java.awt.Color(240, 244, 248));
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        pelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelanggan" }));

        pegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pegawai" }));

        reset.setBackground(new java.awt.Color(90, 106, 125));
        reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(240, 244, 248));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        detail.setBackground(new java.awt.Color(90, 106, 125));
        detail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        detail.setForeground(new java.awt.Color(240, 244, 248));
        detail.setText("Detail");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });

        lblTotalPendapatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalPendapatan.setText("Total Pendapatan: Rp 0");

        cetakStruk.setBackground(new java.awt.Color(90, 106, 125));
        cetakStruk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cetakStruk.setForeground(new java.awt.Color(240, 244, 248));
        cetakStruk.setText("Cetak Struk");
        cetakStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakStrukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCopyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdItem)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblIdItem2))
                        .addComponent(lblIdItem1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdItem4)
                            .addComponent(lblIdItem3)
                            .addComponent(lblIdItem5)
                            .addComponent(lblIdItem6)
                            .addComponent(lblIdItem7))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBiaya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tglTerima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tglSelesai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalKg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCariPesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(detail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdItem)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdItem1)
                            .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdItem2)
                            .addComponent(pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdItem3)
                            .addComponent(tglTerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdItem4)
                            .addComponent(tglSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdItem5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdItem6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdItem7)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 139, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalPendapatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detail)
                            .addComponent(cetakStruk))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset)
                            .addComponent(ubah)
                            .addComponent(simpan))
                        .addGap(29, 29, 29)))
                .addComponent(pnlCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        if (id.getText().isEmpty() || pelanggan.getSelectedIndex() <= 0 || pegawai.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Lengkapi data (ID, Pelanggan, Pegawai)!");
            return;
        }

        try {
            // Ambil Data dari Input GUI
            int id_pes = Integer.parseInt(id.getText());
            
            // Ambil ID Pelanggan dari List
            int idxPel = pelanggan.getSelectedIndex() - 1;
            int idxPeg = pegawai.getSelectedIndex() - 1;
            
            int id_pelanggan = listPelanggan.get(idxPel).getId_pelanggan();
            int id_pegawai = listPegawai.get(idxPeg).getId_pegawai();
            
            // Ambil Tanggal
            java.sql.Timestamp terima_p = new java.sql.Timestamp(tglTerima.getDate().getTime());
            java.sql.Timestamp selesai_p = null;
            if (tglSelesai.getDate() != null) {
                selesai_p = new java.sql.Timestamp(tglSelesai.getDate().getTime());
            }
            
            double kg_p = Double.parseDouble(totalKg.getText());
            double biaya_p = Double.parseDouble(totalBiaya.getText());
            String status_p = status.getSelectedItem().toString();
            
            // Bungkus ke Object Model
            Pesanan p = new Pesanan(id_pes, id_pelanggan, id_pegawai, terima_p, selesai_p, kg_p, biaya_p, status_p);
            
            // Panggil Controller
            DaftarPesananController pc = new DaftarPesananController();
            if (pc.updatePesanan(p)) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");
                resetComponents();
                setInitButtons();
                showTablePesanan(); // Refresh tabel
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format angka salah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void filterStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterStatusItemStateChanged
        // TODO add your handling code here:
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tablePesanan.getModel());
        tablePesanan.setRowSorter(sorter);
        
        String statusPilih = filterStatus.getSelectedItem().toString();
        
        if (statusPilih.equals("SEMUA")) {
            tablePesanan.setRowSorter(null);
        } else {
            RowFilter<TableModel, Object> rf = new RowFilter<TableModel, Object>() {
                public boolean include(RowFilter.Entry<? extends TableModel, ? extends Object> entry) {
                    String statusRow = entry.getStringValue(7);
                    return statusRow.equals(statusPilih);
                }
            };
            sorter.setRowFilter(rf);
        }
        
        // Hitung ulang total pendapatan berdasarkan baris yang tampil
        SwingUtilities.invokeLater(() -> hitungTotalPendapatan());
    }//GEN-LAST:event_filterStatusItemStateChanged

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        int row = tablePesanan.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih salah satu baris terlebih dahulu!");
        } else {
            try {
                
                pelanggan.setEnabled(true);
                pegawai.setEnabled(true);
                tglTerima.setEnabled(true);
                tglSelesai.setEnabled(true);
                totalKg.setEnabled(true);
                totalBiaya.setEnabled(true);
                status.setEnabled(true);
                
                
                id.setText(tablePesanan.getValueAt(row, 0).toString());
                pelanggan.setSelectedItem(tablePesanan.getValueAt(row, 1).toString());
                pegawai.setSelectedItem(tablePesanan.getValueAt(row, 2).toString());
                
                String terima = (String) tablePesanan.getValueAt(row, 3);
                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
                
                try {
                   Date date1 = sdf1.parse(terima);
                    tglTerima.setDate(date1); 
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(null, "Error mem-parsing tanggal diterima: " + e.getMessage());
                }
                
                String selesai = (String) tablePesanan.getValueAt(row, 4);
                SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
                
                try {
                   Date date2 = sdf2.parse(terima);
                    tglSelesai.setDate(date2); 
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(null, "Error mem-parsing tanggal selesai: " + e.getMessage());
                }
                totalKg.setText(tablePesanan.getValueAt(row, 5).toString());
                totalBiaya.setText(tablePesanan.getValueAt(row, 6).toString());
                
                if(tablePesanan.getValueAt(row, 7).toString().equalsIgnoreCase("IN PROGRESS")) {
                    status.setSelectedIndex(0);
                } else {
                    status.setSelectedIndex(1);
                }
                
                

                ubah.setEnabled(false);
                reset.setEnabled(true);
                simpan.setEnabled(true);

            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Error mengambil data pesanan untuk diubah: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        resetComponents();
    }//GEN-LAST:event_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu main_menu = new MainMenu(this.current_pegawai);
        this.dispose();
        main_menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        // TODO add your handling code here:
        int row = tablePesanan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih salah satu pesanan di tabel!");
            return;
        }
        
        try {
            // Ambil ID Pesanan (Kolom 0)
            // convertRowIndexToModel penting jika tabel sedang di-sort/filter
            int viewRow = tablePesanan.getSelectedRow();
            int modelRow = tablePesanan.convertRowIndexToModel(viewRow);
            int idPesanan = Integer.parseInt(tablePesanan.getModel().getValueAt(modelRow, 0).toString());
            
            // Panggil Controller
            DaftarPesananController controller = new DaftarPesananController();
            javax.swing.table.DefaultTableModel detailModel = controller.getDetailItemsModel(idPesanan);
            
            // Tampilkan di Popup
            JTable popupTable = new JTable(detailModel);
            JScrollPane scrollPane = new JScrollPane(popupTable);
            scrollPane.setPreferredSize(new java.awt.Dimension(450, 200));
            
            JOptionPane.showMessageDialog(this, scrollPane, "Rincian Pesanan #" + idPesanan, JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_detailActionPerformed

    private void cetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakStrukActionPerformed
        // TODO add your handling code here:
        int row = tablePesanan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih pesanan yang ingin dicetak!");
            return;
        }

        try {
            // 1. Ambil Data Header dari Tabel yang dipilih
            int modelRow = tablePesanan.convertRowIndexToModel(row);
            
            String idPesanan = tablePesanan.getModel().getValueAt(modelRow, 0).toString();
            String namaPelanggan = tablePesanan.getModel().getValueAt(modelRow, 1).toString();
            String namaPegawai = tablePesanan.getModel().getValueAt(modelRow, 2).toString();
            String tglTerima = tablePesanan.getModel().getValueAt(modelRow, 3).toString();
            String totalBiaya = tablePesanan.getModel().getValueAt(modelRow, 6).toString();
            
            // 2. Ambil Data Detail dari Database (Lewat Controller)
            DaftarPesananController controller = new DaftarPesananController();
            // Kita gunakan method getDetailItemsModel
            javax.swing.table.DefaultTableModel detailModel = controller.getDetailItemsModel(Integer.parseInt(idPesanan));
            
            // 3. Susun Format Struk
            StringBuilder struk = new StringBuilder();
            struk.append("========== LAUNDRY ANDIN  ==========\n");
            struk.append("Jl. Raya Bandung - Sumedang No. 1\n");
            struk.append("====================================\n");
            struk.append("No. Nota   : ").append(idPesanan).append("\n");
            struk.append("Tanggal    : ").append(tglTerima).append("\n");
            struk.append("Pelanggan  : ").append(namaPelanggan).append("\n");
            struk.append("Kasir      : ").append(namaPegawai).append("\n");
            struk.append("------------------------------------\n");
            
            // Loop item detail
            for (int i = 0; i < detailModel.getRowCount(); i++) {
                String namaItem = detailModel.getValueAt(i, 0).toString();
                String berat = detailModel.getValueAt(i, 1).toString(); // "2.0 Kg"
                String subtotal = detailModel.getValueAt(i, 2).toString();
                
                // Format baris: Nama Item (Berat) ... Rp Subtotal
                struk.append(namaItem).append(" (").append(berat).append(" Kg)\n");
                struk.append("   Rp ").append(subtotal).append("\n");
            }
            
            struk.append("------------------------------------\n");
            struk.append("TOTAL BAYAR: Rp ").append(totalBiaya).append("\n");
            struk.append("====================================\n");
            struk.append("   Terima Kasih Atas Kunjungan Anda \n");
            
            // 4. Tampilkan di TextArea dalam JOptionPane
            JTextArea textArea = new JTextArea(struk.toString());
            textArea.setEditable(false);
            textArea.setFont(new java.awt.Font("Monospaced", 0, 12));
            
            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new java.awt.Dimension(300, 400));
            
            JOptionPane.showMessageDialog(this, scrollPane, "Cetak Struk", JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak struk: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_cetakStrukActionPerformed

    private void txtCariPesananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPesananKeyReleased
        // TODO add your handling code here:
        String keyword = txtCariPesanan.getText();
        
        DaftarPesananController controller = new DaftarPesananController();
        javax.swing.table.DefaultTableModel searchModel = controller.searchPesanan(keyword);
        
        tablePesanan.setModel(searchModel);
        
        hitungTotalPendapatan();
    }//GEN-LAST:event_txtCariPesananKeyReleased

    private void hitungTotalPendapatan() {
        double total = 0;
        javax.swing.table.TableModel model = tablePesanan.getModel();
        
        // Loop semua baris yang tampil
        for (int i = 0; i < model.getRowCount(); i++) {
            try {
                // Kolom ke-6 adalah "Total Biaya" (Index dimulai dari 0)
                Object nilai = model.getValueAt(i, 6); 
                if (nilai != null) {
                    total += Double.parseDouble(nilai.toString());
                }
            } catch (Exception e) {
                // Abaikan error parsing
            }
        }
        lblTotalPendapatan.setText("Total Pendapatan: Rp " + String.format("%,.0f", total));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DaftarPesanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetakStruk;
    private javax.swing.JLabel copyright;
    private javax.swing.JButton detail;
    private javax.swing.JComboBox<String> filterStatus;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDaftarPesanan;
    private javax.swing.JLabel lblIdItem;
    private javax.swing.JLabel lblIdItem1;
    private javax.swing.JLabel lblIdItem2;
    private javax.swing.JLabel lblIdItem3;
    private javax.swing.JLabel lblIdItem4;
    private javax.swing.JLabel lblIdItem5;
    private javax.swing.JLabel lblIdItem6;
    private javax.swing.JLabel lblIdItem7;
    private javax.swing.JLabel lblTotalPendapatan;
    private javax.swing.JComboBox<String> pegawai;
    private javax.swing.JComboBox<String> pelanggan;
    private javax.swing.JPanel pnlCopyright;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tablePesanan;
    private com.toedter.calendar.JDateChooser tglSelesai;
    private com.toedter.calendar.JDateChooser tglTerima;
    private javax.swing.JTextField totalBiaya;
    private javax.swing.JTextField totalKg;
    private javax.swing.JTextField txtCariPesanan;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
