/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

/**
 *
 * @author Alesha Naila
 */
public class KelolaPegawai extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaPelanggan.class.getName());

    /** Creates new form KelolaPelanggan */
    public KelolaPegawai() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblPegawai = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblIdPegawai = new javax.swing.JLabel();
        txtIdPegawai = new javax.swing.JTextField();
        lblNamaPegawai = new javax.swing.JLabel();
        txtNamaPegawai = new javax.swing.JTextField();
        lblNoHpPegawai = new javax.swing.JLabel();
        txtNoHpPegawai = new javax.swing.JTextField();
        lblAlamatPegawai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAlamatPegawai = new javax.swing.JTextArea();
        btnSimpanPegawai = new javax.swing.JButton();
        btnHapusPegawai = new javax.swing.JButton();
        btnBatalPegawai = new javax.swing.JButton();
        tblPegawai = new javax.swing.JScrollPane();
        tablePegawai = new javax.swing.JTable();
        txtCariPelanggan = new javax.swing.JTextField();
        pnlCopyright = new javax.swing.JPanel();
        copyright = new javax.swing.JLabel();
        lblUsiaPegawai = new javax.swing.JLabel();
        txtUsiaPegawai = new javax.swing.JTextField();
        lblJenisKelamin = new javax.swing.JLabel();
        comboBoxJenisKelamin = new javax.swing.JComboBox<>();
        lblNoHpPegawai1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 244, 248));

        jPanel3.setBackground(new java.awt.Color(26, 75, 125));

        lblPegawai.setBackground(new java.awt.Color(26, 75, 125));
        lblPegawai.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblPegawai.setForeground(new java.awt.Color(240, 244, 248));
        lblPegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPegawai.setText("Pegawai");
        lblPegawai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 244, 248), 2, true));

        jButton1.setBackground(new java.awt.Color(26, 75, 125));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 244, 248));
        jButton1.setText("Main Menu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblPegawai)
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIdPegawai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdPegawai.setText("ID Pegawai:");

        lblNamaPegawai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNamaPegawai.setText("Nama:");

        lblNoHpPegawai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNoHpPegawai.setText("No. HP:");

        lblAlamatPegawai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAlamatPegawai.setText("Alamat:");

        txtAreaAlamatPegawai.setColumns(20);
        txtAreaAlamatPegawai.setRows(5);
        jScrollPane1.setViewportView(txtAreaAlamatPegawai);

        btnSimpanPegawai.setBackground(new java.awt.Color(76, 175, 80));
        btnSimpanPegawai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSimpanPegawai.setForeground(new java.awt.Color(240, 244, 248));
        btnSimpanPegawai.setText("Simpan");

        btnHapusPegawai.setBackground(new java.awt.Color(211, 47, 47));
        btnHapusPegawai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHapusPegawai.setForeground(new java.awt.Color(240, 244, 248));
        btnHapusPegawai.setText("Hapus");

        btnBatalPegawai.setBackground(new java.awt.Color(90, 106, 125));
        btnBatalPegawai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBatalPegawai.setForeground(new java.awt.Color(240, 244, 248));
        btnBatalPegawai.setText("Batal");

        tablePegawai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tablePegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Usia", "Kelamin", "No. HP", "Alamat", "Tgl. Mulai"
            }
        ));
        tblPegawai.setViewportView(tablePegawai);

        txtCariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariPelangganActionPerformed(evt);
            }
        });

        pnlCopyright.setBackground(new java.awt.Color(51, 51, 51));
        pnlCopyright.setForeground(new java.awt.Color(51, 51, 51));

        copyright.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        copyright.setForeground(new java.awt.Color(240, 244, 248));
        copyright.setText("140810240048 | 140810240066 |140810240080");

        javax.swing.GroupLayout pnlCopyrightLayout = new javax.swing.GroupLayout(pnlCopyright);
        pnlCopyright.setLayout(pnlCopyrightLayout);
        pnlCopyrightLayout.setHorizontalGroup(
            pnlCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCopyrightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyright)
                .addGap(302, 302, 302))
        );
        pnlCopyrightLayout.setVerticalGroup(
            pnlCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCopyrightLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(copyright))
        );

        lblUsiaPegawai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUsiaPegawai.setText("Usia:");

        lblJenisKelamin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblJenisKelamin.setText("Jenis Kelamin:");

        comboBoxJenisKelamin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        comboBoxJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelamin:", "Laki-laki", "Perempuan" }));

        lblNoHpPegawai1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNoHpPegawai1.setText("Tgl. Mulai:");

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCopyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpanPegawai)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatalPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNoHpPegawai1)
                                .addGap(123, 123, 123)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNamaPegawai)
                                .addGap(50, 50, 50)
                                .addComponent(txtNamaPegawai))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIdPegawai)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdPegawai))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsiaPegawai)
                                    .addComponent(lblJenisKelamin)
                                    .addComponent(lblNoHpPegawai)
                                    .addComponent(lblAlamatPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNoHpPegawai)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(txtUsiaPegawai))
                                    .addComponent(comboBoxJenisKelamin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tblPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tblPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdPegawai)
                            .addComponent(txtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamaPegawai)
                            .addComponent(txtNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsiaPegawai)
                            .addComponent(txtUsiaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJenisKelamin)
                            .addComponent(comboBoxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoHpPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoHpPegawai))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlamatPegawai)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNoHpPegawai1)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPegawai)
                    .addComponent(btnHapusPegawai)
                    .addComponent(btnBatalPegawai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(pnlCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaPegawai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPegawai;
    private javax.swing.JButton btnHapusPegawai;
    private javax.swing.JButton btnSimpanPegawai;
    private javax.swing.JComboBox<String> comboBoxJenisKelamin;
    private javax.swing.JLabel copyright;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblAlamatPegawai;
    private javax.swing.JLabel lblIdPegawai;
    private javax.swing.JLabel lblJenisKelamin;
    private javax.swing.JLabel lblNamaPegawai;
    private javax.swing.JLabel lblNoHpPegawai;
    private javax.swing.JLabel lblNoHpPegawai1;
    private javax.swing.JLabel lblPegawai;
    private javax.swing.JLabel lblUsiaPegawai;
    private javax.swing.JPanel pnlCopyright;
    private javax.swing.JTable tablePegawai;
    private javax.swing.JScrollPane tblPegawai;
    private javax.swing.JTextArea txtAreaAlamatPegawai;
    private javax.swing.JTextField txtCariPelanggan;
    private javax.swing.JTextField txtIdPegawai;
    private javax.swing.JTextField txtNamaPegawai;
    private javax.swing.JTextField txtNoHpPegawai;
    private javax.swing.JTextField txtUsiaPegawai;
    // End of variables declaration//GEN-END:variables

}
