/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import config.Koneksi;
import controller.*;
import model.*;
import java.sql.*;
import javax.swing.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alesha Naila
 */
public class PesananBaru extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PesananBaru.class.getName());
    private Pegawai current_pegawai;
    private List<JenisItem> current_ji;
    /**
     * Creates new form PesananBaru
     */
    private java.util.List<Pelanggan> listPelanggan;
    private java.util.List<Pegawai> listPegawai;
    private java.util.List<JenisItem> listJenisItem;

    // Variabel Keranjang Sementara
    private java.util.List<DetailPesanan> keranjangBelanja = new java.util.ArrayList<>();
    private double totalBiayaKeseluruhan = 0;
    private double totalBeratKeseluruhan = 0;

    public PesananBaru() {
        initComponents();
    }
    
    public PesananBaru(Pegawai pegawai) {
        initComponents();
        this.current_pegawai = pegawai;
        setInitComponents();
        loadDataCombo();
    }
    
    private void showTableDetailItem() {
        try {
            if (txtIdPesanan.getText().isEmpty()) return;
            
            int id_pesanan = Integer.parseInt(txtIdPesanan.getText());
            
            DaftarPesananController controller = new DaftarPesananController();
            
            // Set model tabel langsung dari data controller
            tblDetailItem.setModel(controller.getDetailItemsModel(id_pesanan));
            
        } catch (NumberFormatException e) {
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat detail: " + e.getMessage());
        }
    }
    
    private void setInitComponents() {
        baru.setEnabled(true);
        existing.setEnabled(true);
        cek.setEnabled(false);
        
        txtIdPesanan.setEnabled(false);
        btnTambahItem.setEnabled(false);
        btnSimpanPesanan.setEnabled(false);
        btnBatalPesanan.setEnabled(false);
        tglTerima.setEnabled(false);
        comboBoxPelanggan.setEnabled(false);
        comboBoxPegawai.setEnabled(false);
        comboBoxJenis.setEnabled(false);
        txtBeratItem.setEnabled(false);
        
        tglTerima.setDate(null);
        comboBoxPelanggan.setSelectedIndex(0);
        comboBoxPegawai.setSelectedIndex(0);
    }

    private void loadDataCombo() {
        // Load Pelanggan
        PelangganController pc = new PelangganController();
        listPelanggan = pc.getAllPelanggan();
        comboBoxPelanggan.removeAllItems();
        comboBoxPelanggan.addItem("Pilih Pelanggan");
        for (Pelanggan p : listPelanggan) {
            comboBoxPelanggan.addItem(p.getNama_pelanggan());
        }

        // Load Pegawai
        PegawaiController pegC = new PegawaiController();
        listPegawai = pegC.getAllPegawai();
        comboBoxPegawai.removeAllItems();
        comboBoxPegawai.addItem("Pilih Pegawai");
        for (Pegawai p : listPegawai) {
            comboBoxPegawai.addItem(p.getNama_pegawai());
        }

        // Load Jenis Item
        JenisItemController jc = new JenisItemController();
        listJenisItem = jc.getAllJenisItem();
        current_ji = listJenisItem;
        comboBoxJenis.removeAllItems();
        comboBoxJenis.addItem("Pilih Layanan");
        for (JenisItem j : listJenisItem) {
            comboBoxJenis.addItem(j.getNama_item() + " - Rp" + j.getHarga_per_kg()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblPesananBaru = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlCopyright = new javax.swing.JPanel();
        copyright = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIdPesanan = new javax.swing.JLabel();
        txtIdPesanan = new javax.swing.JTextField();
        lblTglDiterima = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxPelanggan = new javax.swing.JComboBox<>();
        comboBoxPegawai = new javax.swing.JComboBox<>();
        tglTerima = new com.toedter.calendar.JDateChooser();
        baru = new javax.swing.JButton();
        existing = new javax.swing.JButton();
        cek = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailItem = new javax.swing.JTable();
        lblJenisItem = new javax.swing.JLabel();
        comboBoxJenis = new javax.swing.JComboBox<>();
        lblBeratItem = new javax.swing.JLabel();
        lblHargaItem = new javax.swing.JLabel();
        txtBeratItem = new javax.swing.JTextField();
        txtHargaItem = new javax.swing.JTextField();
        btnTambahItem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTotalBerat = new javax.swing.JLabel();
        txtTotalBerat = new javax.swing.JTextField();
        lblTotalBerat1 = new javax.swing.JLabel();
        txtTotalBiaya = new javax.swing.JTextField();
        btnSimpanPesanan = new javax.swing.JButton();
        btnBatalPesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 244, 248));

        jPanel3.setBackground(new java.awt.Color(26, 75, 125));

        lblPesananBaru.setBackground(new java.awt.Color(26, 75, 125));
        lblPesananBaru.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblPesananBaru.setForeground(new java.awt.Color(240, 244, 248));
        lblPesananBaru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesananBaru.setText("Pesanan Baru");
        lblPesananBaru.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 244, 248), 2, true));

        jButton1.setBackground(new java.awt.Color(26, 75, 125));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 244, 248));
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPesananBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblPesananBaru)
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCopyright.setBackground(new java.awt.Color(51, 51, 51));
        pnlCopyright.setForeground(new java.awt.Color(51, 51, 51));

        copyright.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        copyright.setForeground(new java.awt.Color(240, 244, 248));
        copyright.setText("140810240048 | 140810240066 |140810240080");

        javax.swing.GroupLayout pnlCopyrightLayout = new javax.swing.GroupLayout(pnlCopyright);
        pnlCopyright.setLayout(pnlCopyrightLayout);
        pnlCopyrightLayout.setHorizontalGroup(
            pnlCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCopyrightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyright)
                .addGap(302, 302, 302))
        );
        pnlCopyrightLayout.setVerticalGroup(
            pnlCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCopyrightLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(copyright))
        );

        jPanel2.setBackground(new java.awt.Color(240, 244, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Pesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 14), new java.awt.Color(90, 106, 125))); // NOI18N

        lblIdPesanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdPesanan.setText("ID Pesanan:");

        txtIdPesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdPesananKeyTyped(evt);
            }
        });

        lblTglDiterima.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTglDiterima.setText("Tgl dan Jam Diterima:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Pilih Pelanggan:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Pegawai Penerima:");

        comboBoxPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelanggan" }));

        comboBoxPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pegawai" }));

        tglTerima.setDateFormatString("yyyy-MM-dd hh:mm:ss");

        baru.setBackground(new java.awt.Color(0, 102, 255));
        baru.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        baru.setForeground(new java.awt.Color(240, 244, 248));
        baru.setText("Tambah ID Baru");
        baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruActionPerformed(evt);
            }
        });

        existing.setBackground(new java.awt.Color(0, 204, 204));
        existing.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        existing.setForeground(new java.awt.Color(240, 244, 248));
        existing.setText("Tambah ke Existing ID");
        existing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingActionPerformed(evt);
            }
        });

        cek.setBackground(new java.awt.Color(90, 106, 125));
        cek.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cek.setForeground(new java.awt.Color(240, 244, 248));
        cek.setText("Cek");
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTglDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblIdPesanan)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(baru)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxPelanggan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxPegawai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIdPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(existing))
                            .addComponent(tglTerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPesanan)
                    .addComponent(txtIdPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cek))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTglDiterima)
                    .addComponent(tglTerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baru)
                    .addComponent(existing))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(240, 244, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Item Pesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(90, 106, 125))); // NOI18N
        jPanel4.setToolTipText("");

        tblDetailItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Berat", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(tblDetailItem);

        lblJenisItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblJenisItem.setText("Jenis Item:");

        comboBoxJenis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        comboBoxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis" }));

        lblBeratItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBeratItem.setText("Berat (Kg):");

        lblHargaItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHargaItem.setText("Total Harga Item (Rp):");

        txtBeratItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBeratItemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBeratItemKeyTyped(evt);
            }
        });

        txtHargaItem.setEditable(false);

        btnTambahItem.setBackground(new java.awt.Color(76, 175, 80));
        btnTambahItem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTambahItem.setForeground(new java.awt.Color(240, 244, 248));
        btnTambahItem.setText("Tambah");
        btnTambahItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblJenisItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHargaItem)
                            .addComponent(lblBeratItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBeratItem)
                            .addComponent(txtHargaItem)
                            .addComponent(btnTambahItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJenisItem)
                            .addComponent(comboBoxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBeratItem)
                            .addComponent(txtBeratItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHargaItem)
                            .addComponent(txtHargaItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahItem))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(240, 244, 248));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 14), new java.awt.Color(90, 106, 125))); // NOI18N

        lblTotalBerat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTotalBerat.setText("TOTAL BERAT:");

        txtTotalBerat.setEditable(false);

        lblTotalBerat1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTotalBerat1.setText("TOTAL BIAYA:");

        txtTotalBiaya.setEditable(false);

        btnSimpanPesanan.setBackground(new java.awt.Color(76, 175, 80));
        btnSimpanPesanan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSimpanPesanan.setForeground(new java.awt.Color(240, 244, 248));
        btnSimpanPesanan.setText("Simpan");
        btnSimpanPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPesananActionPerformed(evt);
            }
        });

        btnBatalPesanan.setBackground(new java.awt.Color(211, 47, 47));
        btnBatalPesanan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBatalPesanan.setForeground(new java.awt.Color(240, 244, 248));
        btnBatalPesanan.setText("Batal");
        btnBatalPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalBerat)
                            .addComponent(lblTotalBerat1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalBerat, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtTotalBiaya))
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSimpanPesanan)
                        .addGap(30, 30, 30)
                        .addComponent(btnBatalPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBerat)
                    .addComponent(txtTotalBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBerat1)
                    .addComponent(txtTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPesanan)
                    .addComponent(btnBatalPesanan))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCopyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahItemActionPerformed
        if (comboBoxJenis.getSelectedIndex() <= 0 || txtBeratItem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih jenis item dan masukkan berat!");
            return;
        }

        try {
            int indexItem = comboBoxJenis.getSelectedIndex() - 1;
            JenisItem itemDipilih = listJenisItem.get(indexItem);
            
            double berat = Double.parseDouble(txtBeratItem.getText());
            double hargaPerKg = itemDipilih.getHarga_per_kg();
            double subtotal = berat * hargaPerKg;

            DetailPesanan detail = new DetailPesanan();
            detail.setId_jenis_item(itemDipilih.getId_jenis_item());
            detail.setBerat_item(berat);
            detail.setTotal_harga_item(subtotal);
            
            keranjangBelanja.add(detail);


            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblDetailItem.getModel();
            
            model.insertRow(0, new Object[]{
                itemDipilih.getNama_item(),
                berat + " Kg",
                "Rp " + String.format("%,.0f", subtotal) // Format rupiah sederhana
            });

            totalBiayaKeseluruhan += subtotal;
            totalBeratKeseluruhan += berat;
            
            txtTotalBiaya.setText(String.format("%.0f", totalBiayaKeseluruhan));
            txtTotalBerat.setText(String.valueOf(totalBeratKeseluruhan));
            
            txtBeratItem.setText("");
            txtHargaItem.setText("");
            comboBoxJenis.setSelectedIndex(0);
            
            comboBoxJenis.setEnabled(true);
            txtBeratItem.setEnabled(true);
            btnTambahItem.setEnabled(true);
            
            btnSimpanPesanan.setEnabled(true);
            btnBatalPesanan.setEnabled(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Berat harus berupa angka yang valid!");
        } catch (Exception e) {
            System.out.println("Error tambah item: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnTambahItemActionPerformed

    private void btnSimpanPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPesananActionPerformed
        if (keranjangBelanja.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Keranjang pesanan masih kosong!");
            return;
        }
        
        // Validasi Header (Pelanggan & Pegawai)
        if (comboBoxPelanggan.getSelectedIndex() <= 0 || comboBoxPegawai.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Mohon pilih Pelanggan dan Pegawai!");
            return;
        }
        
        

        try {
            // Siapkan Data Pesanan
            int indexPelanggan = comboBoxPelanggan.getSelectedIndex() - 1;
            int indexPegawai = comboBoxPegawai.getSelectedIndex() - 1;
            
            Pelanggan pelanggan = listPelanggan.get(indexPelanggan);
            Pegawai pegawai = listPegawai.get(indexPegawai);
            
            Pesanan pesanan = new Pesanan();
            pesanan.setId_pelanggan(pelanggan.getId_pelanggan());
            pesanan.setId_pegawai(pegawai.getId_pegawai());
            
            // Ambil tanggal dari JDateChooser
            if (tglTerima.getDate() != null) {
                pesanan.setTgl_diterima(new java.sql.Timestamp(tglTerima.getDate().getTime()));
            } else {
                pesanan.setTgl_diterima(new java.sql.Timestamp(new java.util.Date().getTime())); // Default now
            }
            
            
            
            pesanan.setTotal_kg(totalBeratKeseluruhan);
            pesanan.setTotal_biaya(totalBiayaKeseluruhan);
            pesanan.setStatus("IN PROGRESS");

            // Panggil Controller Transaksi
            TransaksiController tc = new TransaksiController();
            boolean sukses = tc.simpanTransaksi(pesanan, keranjangBelanja);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Transaksi Berhasil Disimpan!");
                // Reset Form Transaksi
                keranjangBelanja.clear();
                ((javax.swing.table.DefaultTableModel) tblDetailItem.getModel()).setRowCount(0);
                txtTotalBerat.setText("");
                txtTotalBiaya.setText("");
                totalBiayaKeseluruhan = 0;
                totalBeratKeseluruhan = 0;
                
                setInitComponents();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanPesananActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu main_menu = new MainMenu(this.current_pegawai);
        this.dispose();
        main_menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBeratItemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratItemKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) && (evt.getKeyChar()!=evt.VK_PERIOD) && (evt.getKeyChar() != java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Field berat item hanya boleh diisi oleh angka!");
            return;
        }
        
        
    }//GEN-LAST:event_txtBeratItemKeyTyped

    private void btnBatalPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesananActionPerformed
        // TODO add your handling code here:
        btnTambahItem.setEnabled(true);
        txtIdPesanan.setText(null);
        tglTerima.setDate(null);
        comboBoxPelanggan.setSelectedIndex(0);
        comboBoxPegawai.setSelectedIndex(0);
        comboBoxJenis.setEnabled(true);
        txtBeratItem.setEnabled(true);
        txtBeratItem.setText(null);
        txtTotalBerat.setText(null);
        txtTotalBiaya.setText(null);
    }//GEN-LAST:event_btnBatalPesananActionPerformed

    private void baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
        // TODO add your handling code here:
        baru.setEnabled(false);
        existing.setEnabled(false);
        txtIdPesanan.setEnabled(false);
      
        btnTambahItem.setEnabled(true);
        btnSimpanPesanan.setEnabled(false);
        btnBatalPesanan.setEnabled(false);
        tglTerima.setEnabled(true);
        comboBoxPelanggan.setEnabled(true);
        comboBoxPegawai.setEnabled(true);
        comboBoxJenis.setEnabled(true);
        txtBeratItem.setEnabled(true);
        
        tglTerima.setDate(null);
        comboBoxPelanggan.setSelectedIndex(0);
        comboBoxPegawai.setSelectedIndex(0);
        
    }//GEN-LAST:event_baruActionPerformed

    private void existingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingActionPerformed
        // TODO add your handling code here:e
        existing.setEnabled(false);
        baru.setEnabled(false);
        txtIdPesanan.setEnabled(true);    
        cek.setEnabled(true);
        
    }//GEN-LAST:event_existingActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIdPesanan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan ID Pesanan terlebih dahulu!");
                return;
            }

            int id_pesanan = Integer.parseInt(txtIdPesanan.getText());
            
            DaftarPesananController controller = new DaftarPesananController();
            boolean isAda = controller.isPesananExists(id_pesanan);
            
            if (isAda) {
                // ID Ditemukan -> Kunci ID, Buka Inputan
                txtIdPesanan.setEnabled(false);
                btnTambahItem.setEnabled(true);
                
                // Reset & Siapkan komponen lain
                btnSimpanPesanan.setEnabled(false);
                btnBatalPesanan.setEnabled(true);
                
                tglTerima.setEnabled(true);
                comboBoxPelanggan.setEnabled(true);
                comboBoxPegawai.setEnabled(true);
                comboBoxJenis.setEnabled(true);
                txtBeratItem.setEnabled(true);

                showTableDetailItem(); 
                
            } else {
                JOptionPane.showMessageDialog(this, "ID Pesanan " + id_pesanan + " tidak ditemukan!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Field ID Pesanan harus diisi angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_cekActionPerformed

    private void txtIdPesananKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPesananKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Field id pesanan hanya boleh diisi oleh angka!");
        }
    }//GEN-LAST:event_txtIdPesananKeyTyped

    private void txtBeratItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratItemKeyReleased
        // TODO add your handling code here:
        if (comboBoxJenis.getSelectedIndex() <= 0) {
            return;
        }

        // Cek jika kosong, set 0 dan return agar tidak error
        if (txtBeratItem.getText().isEmpty()) {
            txtHargaItem.setText("0");
            return;
        }

        try {
            int choice = comboBoxJenis.getSelectedIndex() - 1;
            JenisItem item = listJenisItem.get(choice); 
            
            double berat = Double.parseDouble(txtBeratItem.getText());
            double hargaPerKg = item.getHarga_per_kg();
            
            double total = hargaPerKg * berat;
            
            txtHargaItem.setText(String.format("%.0f", total));
            
        } catch (NumberFormatException e) {
            txtHargaItem.setText("0"); 
        } catch (Exception e) {
            System.out.println("Error hitung: " + e.getMessage());
        }
    }//GEN-LAST:event_txtBeratItemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PesananBaru().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru;
    private javax.swing.JButton btnBatalPesanan;
    private javax.swing.JButton btnSimpanPesanan;
    private javax.swing.JButton btnTambahItem;
    private javax.swing.JButton cek;
    private javax.swing.JComboBox<String> comboBoxJenis;
    private javax.swing.JComboBox<String> comboBoxPegawai;
    private javax.swing.JComboBox<String> comboBoxPelanggan;
    private javax.swing.JLabel copyright;
    private javax.swing.JButton existing;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBeratItem;
    private javax.swing.JLabel lblHargaItem;
    private javax.swing.JLabel lblIdPesanan;
    private javax.swing.JLabel lblJenisItem;
    private javax.swing.JLabel lblPesananBaru;
    private javax.swing.JLabel lblTglDiterima;
    private javax.swing.JLabel lblTotalBerat;
    private javax.swing.JLabel lblTotalBerat1;
    private javax.swing.JPanel pnlCopyright;
    private javax.swing.JTable tblDetailItem;
    private com.toedter.calendar.JDateChooser tglTerima;
    private javax.swing.JTextField txtBeratItem;
    private javax.swing.JTextField txtHargaItem;
    private javax.swing.JTextField txtIdPesanan;
    private javax.swing.JTextField txtTotalBerat;
    private javax.swing.JTextField txtTotalBiaya;
    // End of variables declaration//GEN-END:variables
}
